apiVersion: apps/v1
kind: Deployment
metadata:
  name: irc-app-audit-logger
  labels:
    app: irc-app-audit-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irc-app-audit-logger
  template:
    metadata:
      labels:
        app: irc-app-audit-logger
    spec:
      containers:
        - name: audit-logger
          image: irc-app-audit-logger:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8004
---
apiVersion: v1
kind: Service
metadata:
  name: irc-app-audit-logger
spec:
  type: ClusterIP
  ports:
    - port: 8004
      targetPort: 8004
  selector:
    app: irc-app-audit-logger
