apiVersion: apps/v1
kind: Deployment
metadata:
  name: irc-app-backend
  labels:
    app: irc-app-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: irc-app-backend
  template:
    metadata:
      labels:
        app: irc-app-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: irc-app-config
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: irc-app-backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8002
  selector:
    app: irc-app-backend
